image: node:8.9.4


cache:
  paths:
  - node_modules/

stages:
  - test

test_deployment:
  stage: test
  script:
   - npm install
   - npm run test
  tags:
    - docker

test_coverage:
  stage: test
  script:
   - npm install
   - npm run test-coverage 
  tags:
   - docker
